# MongoDB Deployment

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
spec:
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec: 
      containers:
      - name: mongodb
        image: mongo:5.0.5
        ports:
          - containerPort: 27017
        env:
          - name: MONGO_INITDB_ROOT_USERNAME
            value: mongouser
          - name: MONGO_INITDB_ROOT_PASSWORD
            value: mongopwd

---
# MongoDB Service
apiVersion: v1
kind: Service
metadata:
  name: mongodb
spec:
  selector:
    app: mongodb
  ports:
  - port: 27017
  type: ClusterIP

---

# Rotten Potatoes Web Application Deployment

apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-rotten-potatoes
spec:
  selector:
    matchLabels: 
      app: web-rotten-potatoes
  template:
    metadata:
      labels:
        app: web-rotten-potatoes
    spec:
      containers:
      - name: web-rotten-potatoes
        image: sonnymarinho/rotten-potatoes:latest
        ports:
        - containerPort: 5000
        env:
        - name: MONGODB_DB
          value: admin
        - name: MONGODB_HOST
          value: mongodb
        - name: MONGODB_PORT
          value: "27017"
        - name: MONGODB_USERNAME
          value: mongouser
        - name: MONGODB_PASSWORD
          value: mongopwd

---

apiVersion: v1
kind: Service
metadata:
  name: web-rotten-potatoes
spec:
  selector: 
    app: web-rotten-potatoes
  ports:
  - port: 80
    targetPort: 5000
    nodePort: 30000
  type: LoadBalancer